### ISSUE TITLE
PCRE non-greedy block is incorrect

### ISSUE THREAD

**Issue by rauschecker** [remram44/regex-cheatsheet#15]
Inside the PCRE column:
- 0 or 1, non-greedy: **?+**       has to be changed to **??**

- 0 or more, non-greedy | ***+**  has to be changed to ***?**

- 1 or more, non-greedy | **++**  has to be changed to **+?**

- Specific number, non-greedy | **{n,m}+ {n,}+** has to be changed to **{n,m}? {n,}?**

(you may verify this yourself by testing it on the console - e.g.:

`echo 'abc00defg00hi00jkl7mn' | pcregrep --color '00.*?00'`
-> abc**00defg00**hi00jkl7mn
)

**Comment by remram44** [comment]
Thanks! Indeed that doesn't look right -- oops!

Please check if #16 is correct and I'll merge it right away.

**Comment by rauschecker** [comment]
Thanks for the quick response.. #16 is correct.
