### ISSUE TITLE
BSD sed seems not working with `\+` (1 or more) in BRE mode

### ISSUE THREAD

**Issue by qianbinbin** [remram44/regex-cheatsheet#25]
Hi there, thank you for your brilliant work.

Here is the question I found in macOS:

```sh
# BSD sed prints nothing
echo '<tag>foobar</tag>' | /usr/bin/sed -n 's|<tag>\(.\+\)</tag>|\1|p'
# GNU sed is okay
echo '<tag>foobar</tag>' | /usr/local/opt/gnu-sed/libexec/gnubin/sed -n 's|<tag>\(.\+\)</tag>|\1|p'
foobar
```

Is the BSD version not working with `\+`? If not, maybe some information should be noted in the cheatsheet.

Correct me if I was wrong.

**Comment by qianbinbin** [comment]
Also a workaround for BSD version: use `..*` instead of `.\+`.

**Comment by remram44** [comment]
Apparently `\+` is only for "enhanced basic REs" as per MacOS `re_format(7)`.

`xx*` and `x\{1,\}` are the only reliable options. Thanks for reporting, I will remove this from the sheet.
