### ISSUE TITLE
Vim: non-word boundary (\B)

### ISSUE THREAD

**Issue by OnlineCop** [remram44/regex-cheatsheet#27]
While vim does not have a native `\B`, would it be worth mentioning that combining the `\<` or `\>` anchors with a negative lookahead `\@!` might be used?

`\<\@!` and `\>\@!` to accomplish the same goal as `\B`.

**Comment by remram44** [comment]
Hi @OnlineCop

That's a good recipe, but I don't know if I should include it. A lot of patterns that are missing in some regex language can be re-built, for example the ones missing from Python. `\<\@!\>\@!` is a little long and I doubt it is ever used in practice.
