### ISSUE TITLE
Please enable GitHub pages

### ISSUE THREAD

**Issue by fishilico** [remram44/regex-cheatsheet#5]
Hi,

Thanks for the work you did! As http://htmlpreview.github.io/?https://github.com/remram44/regex-cheatsheet/blob/master/regex.html does not work well with links browser, I've cloned your repo and set up GitHub pages by following instructions in https://pages.github.com/ for _Project site_. The result is http://fishilico.github.io/regex-cheatsheet/regex.html. As this is quite quick to set up (you only need to rename `master` branch to `gh-pages`, I'm now opening this issue as a "feature request/improvement wish" to ask you if you'd like to make your project available through GitHub pages.

While at it, I've made the HTML page pass the W3C validator (http://validator.w3.org/check?uri=http%3A%2F%2Ffishilico.github.io%2Fregex-cheatsheet%2Fregex.html) and fixed a small typo in the content (`[^[:space;]]` -> `[^[:space:]]`). You can see my commits at https://github.com/fishilico/regex-cheatsheet/commits/gh-pages (I can do a small PR if you want)

Thanks

**Comment by remram44** [comment]
> I've cloned your repo and set up GitHub pages by following instructions in https://pages.github.com/ for Project site.

Yes, that was obvious, wasn't it? I don't know why I didn't use that. I was originally writing this in markdown but the table support was too limited...

Thanks a lot for the fixes! I enabled Github pages and updated the link in the README: [regex cheatsheet](http://remram44.github.io/regex-cheatsheet/regex.html)

I'll see if I can setup automatic HTML validation (#6).
